version: '3.8'

services:
  bot:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:6459709843:AAGDyQqfRitU@db:5432/vstup

  db:
    restart: always
    image: postgres:latest
    volumes:
      - vstupbot_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6459709843:AAGDyQqfRitU
    ports:
      - "5433:5432"

volumes:
  vstupbot_data: